# Generated by Django 4.0.1 on 2022-02-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
